import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — paraphaser.ai",
  description: "Terms of service for paraphaser.ai. Read the rules and guidelines for using our AI writing tools.",
};

export default function TermsPage() {
  return (
    <div className="max-w-[680px] mx-auto px-6 py-12">
      <h1 className="text-[32px] font-extrabold text-white mb-5 tracking-tight">Terms of Service</h1>
      <p className="text-[11px] text-[#4a5068] mb-5">Last updated: February 2026</p>
      <h2 className="text-lg font-bold text-white mt-7 mb-2.5">Acceptance of Terms</h2>
      <p className="text-sm text-[#8892a8] leading-relaxed mb-4">
        By accessing and using paraphaser.ai, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the site.
      </p>
      <h2 className="text-lg font-bold text-white mt-7 mb-2.5">Use of Service</h2>
      <p className="text-sm text-[#8892a8] leading-relaxed mb-4">
        paraphaser.ai provides AI-powered text transformation tools for personal and commercial use. You may use the output generated by our tools freely. However, you are responsible for reviewing all output for accuracy and appropriateness before use.
      </p>
      <h2 className="text-lg font-bold text-white mt-7 mb-2.5">Limitations</h2>
      <p className="text-sm text-[#8892a8] leading-relaxed mb-4">
        Our tools are provided &quot;as is&quot; without warranties of any kind. We do not guarantee that output will be error-free, plagiarism-free, or suitable for any particular purpose. AI-generated content should always be reviewed by a human before publication.
      </p>
      <h2 className="text-lg font-bold text-white mt-7 mb-2.5">Prohibited Uses</h2>
      <p className="text-sm text-[#8892a8] leading-relaxed mb-4">
        You may not use paraphaser.ai to generate content that is illegal, harmful, deceptive, or infringes on the rights of others. Automated scraping, bulk processing through scripts, or any use that places excessive load on our servers is prohibited.
      </p>
      <h2 className="text-lg font-bold text-white mt-7 mb-2.5">Changes to Terms</h2>
      <p className="text-sm text-[#8892a8] leading-relaxed mb-4">
        We reserve the right to update these terms at any time. Continued use of the site constitutes acceptance of any changes.
      </p>
    </div>
  );
}
